-- Function: censocat.migrar_clases_espec_tec_censo_sgm()

-- DROP FUNCTION censocat.migrar_clases_espec_tec_censo_sgm();

CREATE OR REPLACE FUNCTION censocat.migrar_clases_espec_tec_censo_sgm()
  RETURNS void AS
$BODY$

DECLARE
	C_TIPOS CURSOR FOR 
		SELECT ID, NOMBRE, PORCENTUAL, ORDEN
		FROM CENSOCAT.TIPO_ESTRUCTURA;

	C_DETALLE CURSOR FOR
		SELECT ID, TIPO, NOMBRE, PORCENTUAL, ORDEN 
		FROM CENSOCAT.ESTRUCTURA_ESPEC;
	
	ACIERTOS INTEGER := 0;
	PORC BOOLEAN := FALSE;
BEGIN
	FOR C IN C_TIPOS LOOP
		IF(C.PORCENTUAL IS NULL) THEN
			PORC := FALSE;
		ELSE
			PORC := C.PORCENTUAL;
		END IF;
		INSERT INTO APP1.CAT_EDF_CATEG_PROP (ID, NOMBRE, IS_PORCENTUAL, GUI_ORDEN) 
		VALUES(C.ID, C.NOMBRE, PORC, C.ORDEN);
		ACIERTOS := ACIERTOS +1;	
	END LOOP;
	RAISE NOTICE 'TIPO CREADOS %',ACIERTOS;
	ACIERTOS := 0;

	FOR C IN C_DETALLE LOOP
		INSERT INTO APP1.CAT_EDF_PROP (ID, CATEGORIA, NOMBRE) 
		VALUES(C.ID, C.TIPO, C.NOMBRE);
		ACIERTOS := ACIERTOS +1;	
	END LOOP;
	RAISE NOTICE 'ESPECIFICACIONES CREADAS %',ACIERTOS;
END;

$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION censocat.migrar_clases_espec_tec_censo_sgm()
  OWNER TO sisapp;


-- SELECT censocat.migrar_clases_espec_tec_censo_sgm()
-- DELETE FROM APP1.cat_edf_prop
-- truncate table app1.CAT_EDF_CATEG_PROP restart identity cascade;