
CREATE OR REPLACE FUNCTION censocat.migrar_predios_servicios_censo_sgm()
  RETURNS void AS
$BODY$

DECLARE
	C_PREDIOS CURSOR FOR 
		SELECT P.ID, P.PREDIO, P.ALCAN_SANITARIO,P.ALCAN_PLUVIAL,P.ABAST_AGUA,P.CONEX_DOMICILIARIA,P.MEDIDOR_AGUA,P.NUM_MEDIDOR,P.POZO,
			P.ABAST_TANQUERO,P.EE,P.RED_PUB,P.ALUM_PUB,P.MEDIDOR_ENERGIA,P.NUM_MEDIDOR_ENERGIA,P.PLANTA_EE,P.RECOL_BASURA,P.ASEO_CALLES,P.TRANS_PUB,P.INTERNET,
			P.TV_PAG,P.ESTADO,P.ASAN_RED_PUB
		FROM CENSOCAT.PREDIO_SERVICIO P
		INNER JOIN SGM_APP.CAT_PREDIO CP ON CP.ID=P.PREDIO;
	ACIERTOS INTEGER := 0;
	PORC BOOLEAN := FALSE;
	FORMA CHARACTER VARYING(1);
	PREDIO BIGINT;
BEGIN
	FOR C IN C_PREDIOS LOOP
		INSERT INTO SGM_APP.CAT_PREDIO_S6 (ID,PREDIO,TIENE_AGUA_POTABLE, NUM_MEDIDORES_AGUA,TIENE_ELECTRICIDAD,NUM_MED_ELECT,TIENE_INTERNET,
		ABASTE_ELECTRICO,RECOL_BASURA,ALCANTARILLADO_PLUVIAL,ALUMBRADO,ASEO_CALLES,TV_PAG,TPUBLICO,MEDIDOR_EE, MEDIDOR_AGUA, MEDIDOR_ELECTRICO, EVAC_AGUAS_SERV)
		VALUES(DEFAULT,C.PREDIO,C.ABAST_AGUA,(CASE WHEN C.NUM_MEDIDOR IS NOT NULL OR C.NUM_MEDIDOR <> '' THEN 1 ELSE NULL END),C.EE,
			(CASE WHEN C.NUM_MEDIDOR_ENERGIA IS NOT NULL OR C.NUM_MEDIDOR_ENERGIA <> '' THEN 1 ELSE NULL END),
			C.INTERNET,C.PLANTA_EE,33, C.ALCAN_PLUVIAL,C.ALUM_PUB,
			C.ASEO_CALLES,C.TV_PAG,C.TRANS_PUB,C.MEDIDOR_ENERGIA, C.NUM_MEDIDOR, C.NUM_MEDIDOR_ENERGIA, C.ALCAN_SANITARIO);
		ACIERTOS := ACIERTOS +1;
	END LOOP;
	RAISE NOTICE 'SERVICIOS CREADAS %',ACIERTOS;
	ACIERTOS := 0;
END;

$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION censocat.migrar_predios_servicios_censo_sgm()
  OWNER TO sisapp;
