-- Function: censocat.migrar_catalogos_items_censo_sgm()

-- DROP FUNCTION censocat.migrar_catalogos_items_censo_sgm();

CREATE OR REPLACE FUNCTION censocat.migrar_catalogos_items_censo_sgm()
  RETURNS void AS
$BODY$

DECLARE
	C_TIPOS CURSOR FOR 
		SELECT ID, NOMBRE, ESTADO
		FROM CENSOCAT.CATALOGO;

	C_DETALLE CURSOR FOR
		SELECT ID, CATALOGO, VALOR, CODENAME, ESTADO, REFERENCIA
		FROM CENSOCAT.CATALOGO_ITEM;
	
	ACIERTOS INTEGER := 0;
	PORC BOOLEAN := FALSE;
BEGIN
	FOR C IN C_TIPOS LOOP
		INSERT INTO APP1.CTLG_CATALOGO (ID, NOMBRE) 
		VALUES(C.ID, C.NOMBRE);
		ACIERTOS := ACIERTOS +1;	
	END LOOP;
	RAISE NOTICE 'CATALOGOS CREADOS %',ACIERTOS;
	ACIERTOS := 0;

	FOR C IN C_DETALLE LOOP
		INSERT INTO APP1.CTLG_ITEM (ID, CATALOGO, VALOR, CODENAME) 
		VALUES(C.ID, C.CATALOGO, C.VALOR, C.CODENAME);
		ACIERTOS := ACIERTOS +1;	
	END LOOP;
	RAISE NOTICE 'CATALOGO ITEMS CREADAS %',ACIERTOS;
END;

$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION censocat.migrar_catalogos_items_censo_sgm()
  OWNER TO sisapp;


-- SELECT censocat.migrar_catalogos_items_censo_sgm()
-- DELETE FROM APP1.CTLG_CATALOGO
-- truncate table app1.CTLG_CATALOGO restart identity cascade;