-- Function: censocat.migrar_pasi_provincia_canton_parroquia_sgm()

-- DROP FUNCTION censocat.migrar_pasi_provincia_canton_parroquia_sgm();

CREATE OR REPLACE FUNCTION censocat.migrar_pasi_provincia_canton_parroquia_sgm()
  RETURNS void AS
$BODY$

DECLARE
-- PAIS
	C_PAIS CURSOR FOR 
		SELECT DESCRIPCION, PREFIJO, LATITUD, LONGITUD
		FROM CENSOCAT.PAIS;
		-- PROVINCIA
	C_PROVINCIA CURSOR FOR 
		SELECT PAIS, DESCRIPCION, LATITUD, LONGITUD
		FROM CENSOCAT.PROVINCIA;
		-- CANTON
	C_CANTON CURSOR FOR 
		SELECT PROVINCIA, DESCRIPCION, LATITUD, LONGITUD, COD_NAC
		FROM CENSOCAT.CANTON;
		-- PARROQUIA
	C_PARROQUIA CURSOR FOR 
		SELECT CANTON, DESCRIPCION, LATITUD, LONGITUD, COD_NAC
		FROM CENSOCAT.PARROQUIA;	
	ACIERTOS INTEGER := 0;
BEGIN
	FOR C IN C_PAIS LOOP
	--SELECT * FROM app1.cat_pais 
		INSERT INTO APP1.CAT_PAIS (ID, CODIGO, DESCRIPCION) 
		VALUES(DEFAULT, 'EC', C.DESCRIPCION);
		ACIERTOS := ACIERTOS +1;
	END LOOP;
	RAISE NOTICE 'PAISES CREADOS %',ACIERTOS;
	-- PROVINCIA
	ACIERTOS := 0;
	FOR P IN C_PROVINCIA LOOP
	--SELECT * FROM app1.CAT_PROVINCIA 
		INSERT INTO APP1.CAT_PROVINCIA (ID, DESCRIPCION, ID_PAIS) 
		VALUES(DEFAULT, P.DESCRIPCION, P.PAIS);
		ACIERTOS := ACIERTOS +1;
	END LOOP;
	RAISE NOTICE 'PROVINCIAS CREADAS %',ACIERTOS;
	-- CANTON
	ACIERTOS := 0;
	FOR P IN C_CANTON LOOP
	--SELECT * FROM app1.CAT_CANTON 
		INSERT INTO APP1.CAT_CANTON (ID, NOMBRE, ID_PROVINCIA, CODIGO_NACIONAL, ID_CANTON_REGISTRO, ESTADO, ID_SIRE) 
		VALUES(DEFAULT, P.DESCRIPCION, P.PROVINCIA, P.COD_NAC, NULL, TRUE, NULL);
		ACIERTOS := ACIERTOS +1;
	END LOOP;
	RAISE NOTICE 'CANTONES CREADOS %',ACIERTOS;
	-- PARROQUIA
	ACIERTOS := 0;
	FOR C IN C_PARROQUIA LOOP
	--SELECT * FROM app1.CAT_PARROQUIA 
		INSERT INTO APP1.CAT_PARROQUIA (ID, DESCRIPCION, CODIGO_PARROQUIA, TIPO, ID_CANTON, ESTADO) 
		VALUES(DEFAULT, C.DESCRIPCION, NULL, NULL, C.CANTON, TRUE);
		ACIERTOS := ACIERTOS +1;
	END LOOP;
	RAISE NOTICE 'PARROQUIAS CREADAS %',ACIERTOS;
END;

$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION censocat.migrar_pasi_provincia_canton_parroquia_sgm()
  OWNER TO sisapp;
  
--SELECT * FROM censocat.pais 
--SELECT * FROM censocat.provincia 
--SELECT * FROM censocat.canton 
--SELECT * FROM censocat.parroquia

-- SELECT censocat.migrar_pasi_provincia_canton_parroquia_sgm()
-- truncate table app1.cat_pais restart identity cascade;