-- Function: censocat.migrar_predios_escrituras_censo_sgm()

-- DROP FUNCTION censocat.migrar_predios_escrituras_censo_sgm();

CREATE OR REPLACE FUNCTION censocat.migrar_predios_escrituras_censo_sgm()
  RETURNS void AS
$BODY$

DECLARE
	C_PREDIOS CURSOR FOR 
		SELECT ID, PREDIO, NUM_FICHA, NOTARIA, FECHA_ESCRITURA, FOLIO_DESDE, FOLIO_HASTA, NUM_REPERTORIO, FECHA_INSCRIPCION, CUANTIA,FEC_CRE, ESTADO, AREA, NUM_INSCRIPCION
		FROM CENSOCAT.PREDIO_ESCRITURA P;
	ACIERTOS INTEGER := 0;
	PORC BOOLEAN := FALSE;
	FORMA CHARACTER VARYING(1);
BEGIN
	FOR C IN C_PREDIOS LOOP
		INSERT INTO SGM_APP.CAT_ESCRITURA (ID_ESCRITURA, PREDIO, NUM_FICHA, FEC_ESCRITURA, NUM_REPERTORIO, FOLIO_DESDE, FOLIO_HASTA, AREA_SOLAR, ESTADO, NOTARIA)
		VALUES(DEFAULT, C.PREDIO, C.NUM_FICHA, C.FECHA_ESCRITURA, C.NUM_REPERTORIO, C.FOLIO_DESDE, C.FOLIO_HASTA,C.AREA, 'A', C.NOTARIA);	
		ACIERTOS := ACIERTOS +1;	
	END LOOP;
	RAISE NOTICE 'ESCRITURAS CREADAS %',ACIERTOS;
	ACIERTOS := 0;
END;

$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION censocat.migrar_predios_escrituras_censo_sgm()
  OWNER TO sisapp;


-- SELECT censocat.migrar_predios_escrituras_censo_sgm() --4813
-- DELETE FROM APP1.CAT_PREDIO
-- truncate table APP1.CAT_ESCRITURA restart identity cascade;
-- SELECT COUNT(*) FROM CENSOCAT.PREDIO_ESCRITURA -- 4813