-- Function: censocat.migrar_predios_censo_sgm()

-- DROP FUNCTION censocat.migrar_predios_censo_sgm();

CREATE OR REPLACE FUNCTION censocat.migrar_predios_censo_sgm()
  RETURNS void AS
$BODY$

DECLARE
	C_PREDIOS CURSOR FOR 
		SELECT P.ID, P.NUM_PREDIO, P.PROVINCIA, P.CANTON, P.PARROQUIA, P.SECTOR, P.MZ, P.SOLAR, 
			P.DIV1, P.DIV2, P.DIV3, P.DIV4, P.DIV5, P.DIV6, P.DIV7, P.DIV8, P.DIV9, P.PHV, P.PHH, 
			P.PROP_HORIZONTAL, P.UBICACION, P.CIUDADELA, P.TIPO_PROPIEDAD, P.USO_PREDIO, 
			P.TOPOGRAFIA, 
			(CASE 
			       WHEN P.TIPO_SUELO = 8 THEN 3
			       WHEN P.TIPO_SUELO = 9 THEN 2
			       WHEN P.TIPO_SUELO = 10 THEN 6
			       WHEN P.TIPO_SUELO = 12 THEN 7 END) AS TIPO_SUELO, 
			(CASE 
				WHEN P.FORMA = 125 THEN '1'
				WHEN P.FORMA = 126 THEN '2'
				WHEN P.FORMA = 127 THEN '0'
			END) AS FORMA,
			P.SEC_URB, P.MZ_URB, P.SOLAR_URB, P.EDIFICIO, 
			P.DIRECCION, P.PLANTA, P.AV_CALLE_P, P.AV_CALLE_I, P.AV_CALLE_URB, P.OBSERVACIONES, 
			P.USR_CRE, P.FEC_CRE, P.USR_ACT, P.FEC_ACT, P.ESTADO, P.ALICUOTA, P.AREA_LEVANTADA, 
			P.CDLA, P.TIPO_CONJUNTO, P.TIPO_USO_EDIF, P.NUM_EDIFICIO, P.AV_CALLE_NUM, 
			P.ARRENDADO, P.FEC_ARRIENDO, P.MZ_DIV, P.AV_CALLE_S, P.NUEVO, P.CERRAMIENTO, 
			P.USO_SUELO, P.PERMISO_CONST, P.NUM_INSPECCION, P.FECHA_INSPECCION, P.FECHA_PERMISO, 
			P.LOCALIZACION, P.CONSTRUCTIVIDAD, P.ETAPA_EDIF, P.PROCESADOS, 0.0 AS COORDX, 0.00 AS COORDY, NULL AS HABITANTES, T.ZONA
		FROM CENSOCAT.PREDIO P
		INNER JOIN CENSOCAT.ORDEN_DET D ON D.PREDIO = P.ID
		INNER JOIN CENSOCAT.ORDEN_TRABAJO T ON T.ID = D.ORDEN;
	ACIERTOS INTEGER := 0;
	PORC BOOLEAN := FALSE;
	FORMA CHARACTER VARYING(1);
BEGIN
	FOR C IN C_PREDIOS LOOP
		
		INSERT INTO APP1.CAT_PREDIO (ID, NUM_PREDIO, ZONA, SECTOR, MZ, SOLAR, CIUDADELA, CDLA, TOPOGRAFIA_SOLAR, TIPO_SUELO, FORMA_SOLAR, URB_SECNEW, URB_MZ, URB_SOLARNEW, CALLE, CALLE_AV, CALLE_S, INST_CREACION, ALICUOTA_SAC, AREA_SOLAR, TIPO_CONJUNTO, COORDX, COORDY) 
		VALUES(C.ID, C.NUM_PREDIO, C.ZONA, C.SECTOR, C.MZ, C.SOLAR, C.CIUDADELA, 0, C.TOPOGRAFIA, C.TIPO_SUELO, C.FORMA,C.SEC_URB, C.MZ_URB, C.SOLAR_URB, C.AV_CALLE_P,C.AV_CALLE_I,C.AV_CALLE_S,C.FEC_CRE,C.ALICUOTA, C.AREA_LEVANTADA, 1,C.COORDX, C.COORDY);
		ACIERTOS := ACIERTOS +1;	
	END LOOP;
	RAISE NOTICE 'PREDIOS CREADOS %',ACIERTOS;
	ACIERTOS := 0;	
END;

$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION censocat.migrar_predios_censo_sgm()
  OWNER TO sisapp;


-- SELECT censocat.migrar_predios_censo_sgm() -- 4556
-- DELETE FROM APP1.CAT_PREDIO
-- truncate table app1.CAT_PREDIO restart identity cascade;
-- SELECT COUNT(*) FROM censocat.predio 4557 
