

CREATE OR REPLACE FUNCTION censocat.update_avaluos()
  RETURNS void AS
$BODY$
DECLARE TIPO_CONJ BIGINT;
DECLARE
	C_PREDIO CURSOR FOR 
		select id, avaluo_solar, avaluo_construccion from censocat.predio ;
	ACIERTOS INTEGER := 0;
	TPERSONA BOOLEAN := FALSE;
BEGIN
	FOR T IN C_PREDIO LOOP

		UPDATE SGM_APP.CAT_PREDIO SET AVALUO_SOLAR = T.AVALUO_SOLAR , AVALUO_CONSTRUCCION = T.AVALUO_CONSTRUCCION WHERE SGM_APP.CAT_PREDIO.ID = T.ID;	
		
	END LOOP;
END;

$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;
ALTER FUNCTION censocat.update_avaluos()
  OWNER TO sisapp;

SELECT * FROM SGM_APP.CAT_PREDIO LIMIT 

SELECT censocat.update_avaluos()